package forms;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import library.Read;
import components.SortDepartment;
import library.Writer;
import pojo.Data;
import pojo.Department;

/**
 *
 * @author Juanito C. Dela Cerna Jr. October 4 - 7, 2021
 */
public class AddDepartmentForm extends Form {

    private int selectedDepartmentId = 0;

    /**
     * Creates new form AddDepartment
     */
    public AddDepartmentForm() {
        initComponents();
        departmentTable();
    }

    /**
     * Load position table
     */
    public void departmentTable() {
        // Position table
        DefaultTableModel table = (DefaultTableModel) jTableDepartment.getModel();
        // Set the initial table row count
        table.setRowCount(0);
        // Get first the existing data
        ArrayList<Department> departmentList = new Read(Data.DEPARTMENT).departmentList();
        // Sort
        Collections.sort(departmentList, new SortDepartment().reversed());
        for (Department department : departmentList) {
            // Vector array
            Vector v = new Vector();
            v.add(department.getId());
            v.add(department.getDepartment());
            // Add the vector array object
            table.addRow(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDepartment = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDepartment = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Department");
        setAlwaysOnTop(true);
        setName("Add Departmet"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("DEPARTMENT:");

        jButtonSave.setText("SAVE");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jTableDepartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "DEPARTMENT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDepartmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDepartment);
        if (jTableDepartment.getColumnModel().getColumnCount() > 0) {
            jTableDepartment.getColumnModel().getColumn(0).setMinWidth(40);
            jTableDepartment.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jLabel2.setText("* Double click the table row to update the department ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if (jTextFieldDepartment.getText().length() > 0) {
            // Get first the existing data
            ArrayList<Department> departmentList = new Read(Data.DEPARTMENT).departmentList();
            // Sort the list first
            Collections.sort(departmentList, new SortDepartment().reversed());

            // Create a new department instance 
            Department department = new Department();
            // If the departmentList is empty, set the rowId to 1
            // If departmentList is not empty get the value in index zero to add 1 
            int rowId = departmentList.isEmpty() ? 1 : departmentList.get(0).getId() + 1;
            department.setId(rowId);
            department.setDepartment(jTextFieldDepartment.getText());
            // Add to departmentList
            departmentList.add(department);

            // Write the text into file
            Writer writer = new Writer(Data.DEPARTMENT);
            writer.addDepartment(departmentList);
            
            // Show a success message
            JOptionPane.showMessageDialog(this, "Department table is successfully "
                    + "updated", "Info", JOptionPane.INFORMATION_MESSAGE);
            
            // Cleat the input field
            jTextFieldDepartment.setText("");
            jTextFieldDepartment.requestFocus();

            // Populate the data again
            departmentTable();
        } else {
            JOptionPane.showMessageDialog(this, "Please a input a Departmen"
                    + " name", "Warning", JOptionPane.WARNING_MESSAGE);
            jTextFieldDepartment.requestFocus();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTableDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDepartmentMouseClicked
        // Department table
         DefaultTableModel table = (DefaultTableModel) jTableDepartment.getModel();
        // get the selected department id
        selectedDepartmentId = Integer.parseInt(table.getValueAt(
                jTableDepartment.getSelectedRow(), 0).toString());
        
        // Show input dialog to ask the user to upddate the department
        String result = (String)JOptionPane.showInputDialog(this, "Department", "Update",
                JOptionPane.QUESTION_MESSAGE, null, null, 
                table.getValueAt(jTableDepartment.getSelectedRow(), 1).toString());
        
        if(result != null) {
            ArrayList<Department> departmentsList = new Read(Data.DEPARTMENT).departmentList();
            ArrayList<Department> newDepartmentsList = new ArrayList<>();
            for(Department departments: departmentsList) {
                Department d = new Department();
                if(selectedDepartmentId == departments.getId()) {
                    d.setId(selectedDepartmentId);
                    d.setDepartment(result);
                } else {
                    d.setId(departments.getId());
                    d.setDepartment(departments.getDepartment());
                }
                newDepartmentsList.add(d);
            }
            // Write the data again
            Writer w = new Writer(Data.DEPARTMENT);
            w.addDepartment(newDepartmentsList);
            // Load the table again
            departmentTable();
        } 
    }//GEN-LAST:event_jTableDepartmentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDepartmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDepartmentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDepartment;
    private javax.swing.JTextField jTextFieldDepartment;
    // End of variables declaration//GEN-END:variables
}
