package forms;

import components.ComboItem;
import components.SortDepartment;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.DefaultButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import library.Read;
import components.SortEmployee;
import components.SortPosition;
import java.time.LocalDate;
import javax.swing.JRadioButton;
import library.Writer;
import pojo.Data;
import pojo.Department;
import pojo.Employee;
import pojo.Position;
import pojo.Records;

/**
 *
 * @author Juanito C. Dela Cerna Jr. October 4 - 7, 2021
 */
public class AddEmployeeForm extends Form {

    private int selectedEmployeeId;
    private int selectedRowEmployeeId;
    private int selecetedDepartmentId;
    private String employeeType;
    private int selectedPositionId;

    /**
     * Creates new form AddEmployee
     */
    public AddEmployeeForm() {
        initComponents();
        // default value
        selectedEmployeeId = 0;
        selectedRowEmployeeId = 0;

        // Table
        employeeTable();
        // Initialize components
        radioButtonEmployeeType(jRadioButtonTeaching);
        // Department
        comboBoxDepartment();
        // Default
        // selecetedDepartmentId = 1;
        // Position
        comboBoxPosition(selecetedDepartmentId);
    }

    /**
     * Reset
     */
    public void clear() {
        radioButtonEmployeeType(jRadioButtonTeaching);
        jTextFieldEmployeeId.setText("");
        jTextFieldFirstName.setText("");
        jTextFieldSurename.setText("");
        //comboBoxDepartment();
        //comboBoxPosition(selecetedDepartmentId);
        jTextFieldRate.setText("");
        selectedEmployeeId = 0;
        selectedRowEmployeeId = 0;
    }

    /**
     * Initialize the combo box department
     */
    public void comboBoxDepartment() {
        // Clear combobox department
        jComboBoxDepartment.removeAllItems();
        ArrayList<Department> departmentsList = new Read(Data.DEPARTMENT).departmentList();
        Collections.sort(departmentsList, new SortDepartment().reversed());
        DefaultComboBoxModel jCDepartment = (DefaultComboBoxModel) jComboBoxDepartment.getModel();
        for (Department d : departmentsList) {
            jCDepartment.addElement(new ComboItem(d.getId(), d.getDepartment()));
        }
    }

    /**
     * Initialize the combo box department
     */
    public void comboBoxPosition(int selectedDepartment) {
        // Clear combobox position
        jComboBoxPosition.removeAllItems();

        ArrayList<Position> positionList = new Read(Data.POSITION).positionList();
        Collections.sort(positionList, new SortPosition().reversed());
        DefaultComboBoxModel jCPosition = (DefaultComboBoxModel) jComboBoxPosition.getModel();
        for (Position p : positionList) {
            if (selectedDepartment == p.getDepartmentId()) {
                jCPosition.addElement(new ComboItem(p.getId(), p.getPosition()));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxPosition = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxDepartment = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSurename = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jRadioButtonTeaching = new javax.swing.JRadioButton();
        jRadioButtonNonTeaching = new javax.swing.JRadioButton();
        jTextFieldEmployeeId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldRate = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPaneTable = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmployee = new javax.swing.JTable();
        jButtonSave = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Employee");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jComboBoxPosition.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPositionItemStateChanged(evt);
            }
        });

        jLabel4.setText("POSITION:");

        jComboBoxDepartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDepartmentItemStateChanged(evt);
            }
        });

        jLabel3.setText("DEPARTMENT:");

        jLabel2.setText("SURENAME:");

        jLabel1.setText("FIRST NAME:");

        jRadioButtonTeaching.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonTeaching.setText("Teaching");
        jRadioButtonTeaching.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonTeachingItemStateChanged(evt);
            }
        });

        jRadioButtonNonTeaching.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButtonNonTeaching.setText("Non - Teaching");
        jRadioButtonNonTeaching.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonNonTeachingItemStateChanged(evt);
            }
        });

        jLabel6.setText("EMPLOYEE ID:");

        jLabel5.setText("EMPLOYEE TYPE:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("RATE PER HOUR / MONTHLY");

        jTextFieldRate.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldRate, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSurename, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jRadioButtonTeaching)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonNonTeaching)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTeaching)
                    .addComponent(jRadioButtonNonTeaching)
                    .addComponent(jLabel5))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSurename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPaneTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPaneTable.setAutoscrolls(true);

        jTableEmployee.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "ID", "NAME", "TYPE", "DEPARTMENT", "POSITION", "REGISTERED (DATE)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmployee.setGridColor(new java.awt.Color(255, 255, 255));
        jTableEmployee.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmployee);
        if (jTableEmployee.getColumnModel().getColumnCount() > 0) {
            jTableEmployee.getColumnModel().getColumn(0).setMinWidth(30);
            jTableEmployee.getColumnModel().getColumn(0).setMaxWidth(30);
            jTableEmployee.getColumnModel().getColumn(1).setMinWidth(40);
            jTableEmployee.getColumnModel().getColumn(1).setMaxWidth(50);
            jTableEmployee.getColumnModel().getColumn(2).setMinWidth(150);
            jTableEmployee.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        jScrollPaneTable.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPaneTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
        );

        jButtonSave.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N
        jButtonSave.setText("ADD");
        jButtonSave.setToolTipText("Aadd new employee");
        jButtonSave.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonSave.setIconTextGap(1);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonEdit.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/redact.png"))); // NOI18N
        jButtonEdit.setText("EDIT");
        jButtonEdit.setToolTipText("Edit employee information");
        jButtonEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonEdit.setIconTextGap(1);
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/select.png"))); // NOI18N
        jButtonDelete.setText("DELETE");
        jButtonDelete.setToolTipText("Delete employee infortion");
        jButtonDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButtonDelete.setIconTextGap(1);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabel8.setText("* Double click the table row to Edit / Delete the record");
        jLabel8.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CLEAR");
        jButton1.setToolTipText("Clear selected record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit)
                            .addComponent(jButtonSave)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDepartmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDepartmentItemStateChanged
        try {
            DefaultComboBoxModel cBox = (DefaultComboBoxModel) jComboBoxDepartment.getModel();
            // Class object
            Object item = cBox.getSelectedItem();
            // Get the selected department id
            selecetedDepartmentId = ((ComboItem) item).getKey();

            // load the position table
            comboBoxPosition(selecetedDepartmentId);
        } catch (NullPointerException e) {
            // System.out.println(e.getMessage());
            // Do nothin, this occur when the combobox throw a null value
        }
    }//GEN-LAST:event_jComboBoxDepartmentItemStateChanged

    /**
     * Radio button for employee type
     */
    public void radioButtonEmployeeType(JRadioButton jRadioButton) {
        ButtonGroup buttonGroupEmployeeType = new ButtonGroup();
        buttonGroupEmployeeType.add(jRadioButtonTeaching);
        buttonGroupEmployeeType.add(jRadioButtonNonTeaching);
        DefaultButtonModel radioButtonModel = (DefaultButtonModel) jRadioButton.getModel();
        buttonGroupEmployeeType.setSelected(radioButtonModel, true);
    }

    /**
     * Get the department
     *
     * @param departmentId
     */
    public String getDepartment(int departmentId) {
        String result = "";
        // Department combobox
        ArrayList<Department> departmentsList = new Read(Data.DEPARTMENT).departmentList();
        // Clear the combobox first
        for (Department d : departmentsList) {
            if (departmentId == d.getId()) {
                result = d.getDepartment();
            }
        }
        return result;
    }

    /**
     * Get the position
     *
     * @param positionId
     */
    public String getPositio(int positionId) {
        String result = "";
        // Department combobox
        ArrayList<Position> PositionsList = new Read(Data.POSITION).positionList();
        // Clear the combobox first
        for (Position p : PositionsList) {
            if (positionId == p.getId()) {
                result = p.getPosition();
            }
        }
        return result;
    }

    /**
     * Employee table
     *
     */
    public void employeeTable() {
        // Employee table
        DefaultTableModel table = (DefaultTableModel) jTableEmployee.getModel();
        table.setRowCount(0);
        // Get the employee list
        ArrayList<Employee> employeeList = new Read(Data.EMPLOYEE).employeeList();
        Collections.sort(employeeList, new SortEmployee().reversed());

        for (Employee e : employeeList) {
            Vector v = new Vector();
            v.add(e.getId());
            v.add(e.getEmployeeId());
            String name = e.getFirstName() + " " + e.getSureName();
            v.add(name);
            v.add(e.getEmployeeTye());
            v.add(getDepartment(e.getDepartmentId()));
            v.add(getPositio(e.getPositionId()));
            v.add(e.getCreateAt());
            table.addRow(v);
        }
    }

    /**
     * Check employee id
     *
     * @param employeeId
     */
    public int findEmployeeById(int employeeId) {
        // Get the employee list
        ArrayList<Employee> employeeList = new Read(Data.EMPLOYEE).employeeList();
        for (Employee e : employeeList) {
            if (employeeId == e.getEmployeeId()) {
                return 1;
            }
        }
        return 0;
    }

    /**
     * Validate all the user input
     *
     * @return 0 to input again and 1 for valid input
     */
    public int inputValidation() {
        String employeeId = idFieldValidation("Employee Id", jTextFieldEmployeeId);
        if (employeeId.isEmpty()) {
            return 0;
        }

        String firstName = textFieldValidation("First name", jTextFieldFirstName);
        if (firstName.isEmpty()) {
            return 0;
        }

        String surename = textFieldValidation("Surename", jTextFieldSurename);
        if (surename.isEmpty()) {
            return 0;
        }

        String rate = numberFieldValidation("Rate", jTextFieldRate);
        if (rate.isEmpty()) {
            return 0;
        }

        return 1;
    }

    private void jRadioButtonTeachingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonTeachingItemStateChanged
        employeeType = "Teaching";
    }//GEN-LAST:event_jRadioButtonTeachingItemStateChanged

    private void jRadioButtonNonTeachingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonNonTeachingItemStateChanged
        employeeType = "Non - Teaching";
    }//GEN-LAST:event_jRadioButtonNonTeachingItemStateChanged

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // Validate the input first
        if (inputValidation() == 1) {
            int employeeId = Integer.parseInt(jTextFieldEmployeeId.getText());
            if (findEmployeeById(employeeId) == 0) {
                ArrayList<Employee> employeeList = new Read(Data.EMPLOYEE).employeeList();
                // Sort the list first
                Collections.sort(employeeList, new SortEmployee().reversed());
                Employee e = new Employee();
                e.setId(employeeList.isEmpty() ? 1 : employeeList.get(0).getId() + 1);
                e.setFirstName(jTextFieldFirstName.getText());
                e.setSureName(jTextFieldSurename.getText());
                e.setEmployeeId(Integer.parseInt(jTextFieldEmployeeId.getText()));
                e.setEmployeeTye(employeeType);
                e.setRate(Float.parseFloat(jTextFieldRate.getText()));
                e.setDepartmentId(selecetedDepartmentId);
                e.setPositionId(selectedPositionId);
                e.setCreateAt(String.valueOf(LocalDate.now()));

                employeeList.add(e);
                // write the data
                Writer w = new Writer(Data.EMPLOYEE);
                w.addEmployee(employeeList);
                // Clear
                clear();
                // Load the table
                employeeTable();
                JOptionPane.showMessageDialog(this, "Employee has been successfully"
                        + " added", "Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "The employee id " + employeeId
                        + " is already recorded", "Info", JOptionPane.INFORMATION_MESSAGE);
                jTextFieldEmployeeId.requestFocus();
            }
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jComboBoxPositionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPositionItemStateChanged
        try {
            DefaultComboBoxModel cBox = (DefaultComboBoxModel) jComboBoxPosition.getModel();
            Object item = cBox.getSelectedItem();
            // Get the selected department id
            selectedPositionId = ((ComboItem) item).getKey();
        } catch (NullPointerException e) {
            // System.out.println("");
            // Do nothing
        }
    }//GEN-LAST:event_jComboBoxPositionItemStateChanged

    private void jTableEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmployeeMouseClicked
        try {
            // Employee table
            DefaultTableModel table = (DefaultTableModel) jTableEmployee.getModel();
            // Selected row
            int selected = jTableEmployee.getSelectedRow();
            // Get the selected employee id for edit function, this employee id is the row nunber of the table
            selectedEmployeeId = Integer.parseInt(table.getValueAt(selected, 0).toString());
            // This the inputed employee id
            selectedRowEmployeeId = Integer.parseInt(table.getValueAt(selected, 1).toString());

            ArrayList<Employee> employees = new Read(Data.EMPLOYEE).employeeList();
            for (Employee e : employees) {
                if (selectedEmployeeId == e.getId()) {
                    jTextFieldEmployeeId.setText(String.valueOf(e.getEmployeeId()));
                    jTextFieldFirstName.setText(e.getFirstName());
                    jTextFieldSurename.setText(e.getSureName());
                    // For employee type
                    if (table.getValueAt(selected, 3).toString().equals("Teaching")) {
                        radioButtonEmployeeType(jRadioButtonTeaching);
                    } else {
                        radioButtonEmployeeType(jRadioButtonNonTeaching);
                    }

                    // Department combobox
                    ArrayList<Department> departmentsList = new Read(Data.DEPARTMENT).departmentList();
                    Collections.sort(departmentsList, new SortDepartment().reversed());
                    DefaultComboBoxModel jCDepartment = (DefaultComboBoxModel) jComboBoxDepartment.getModel();
                    // Clear the combobox first
                    jComboBoxDepartment.removeAllItems();
                    for (Department d : departmentsList) {
                        // Object for comboItem department
                        Object obj = new ComboItem(d.getId(), d.getDepartment());
                        if (e.getDepartmentId() == d.getId()) {
                            // Set the selected item
                            jCDepartment.setSelectedItem(obj);
                            jCDepartment.addElement(obj);
                        } else {
                            // Add the reamining items
                            jCDepartment.addElement(obj);
                        }
                    }

                    // Position combobox
                    ArrayList<Position> positionsList = new Read(Data.POSITION).positionList();
                    Collections.sort(positionsList, new SortPosition().reversed());
                    DefaultComboBoxModel jCPosition = (DefaultComboBoxModel) jComboBoxPosition.getModel();
                    // Clear the combobox first
                    jComboBoxPosition.removeAllItems();
                    for (Position p : positionsList) {
                        // Object for comboItem position
                        Object obj = new ComboItem(p.getId(), p.getPosition());
                        if (e.getPositionId() == p.getId()) {
                            // Set the selected item
                            jCPosition.setSelectedItem(obj);
                            jCPosition.addElement(obj);
                        } else {
                            // Add the reamining items
                            jCPosition.addElement(obj);
                        }
                    }

                    jTextFieldRate.setText(String.valueOf(e.getRate()));
                }
            }
        } catch (NullPointerException e) {
            // System.out.println(e.getMessage());
            // Do nothing
        }
    }//GEN-LAST:event_jTableEmployeeMouseClicked

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        try {
            if (selectedEmployeeId != 0) {
                if (inputValidation() == 1) {

                    // Show input confirm dialog to ask the user 
                    int result = JOptionPane.showConfirmDialog(this,
                            "Are you sure you want to update the selected record with id " + selectedRowEmployeeId,
                            "Update", JOptionPane.WARNING_MESSAGE);

                    if (result == 0) {
                        ArrayList<Employee> employeesList = new Read(Data.EMPLOYEE).employeeList();
                        ArrayList<Employee> newEmployeeList = new ArrayList<>();
                        for (Employee employee : employeesList) {
                            Employee e = new Employee();
                            if (selectedEmployeeId == employee.getId()) {
                                // Update the selecte employee
                                e.setId(selectedEmployeeId);
                                e.setEmployeeId(Integer.parseInt(jTextFieldEmployeeId.getText()));
                                e.setFirstName(jTextFieldFirstName.getText());
                                e.setSureName(jTextFieldSurename.getText());
                                e.setEmployeeTye(employeeType);
                                e.setRate(Float.parseFloat(jTextFieldRate.getText()));
                                e.setDepartmentId(selecetedDepartmentId);
                                e.setPositionId(selectedPositionId);
                                e.setCreateAt(String.valueOf(LocalDate.now()));
                            } else {
                                // Set the existing employee
                                e.setId(employee.getId());
                                e.setEmployeeId(employee.getEmployeeId());
                                e.setFirstName(employee.getFirstName());
                                e.setSureName(employee.getSureName());
                                e.setEmployeeTye(employee.getEmployeeTye());
                                e.setRate(employee.getRate());
                                e.setDepartmentId(employee.getDepartmentId());
                                e.setPositionId(employee.getPositionId());
                                e.setCreateAt(employee.getCreateAt());
                            }
                            newEmployeeList.add(e);
                        }
                        // Write the data again
                        Writer w = new Writer(Data.EMPLOYEE);
                        w.addEmployee(newEmployeeList);
                        // Clear
                        clear();
                        // Load the table
                        employeeTable();
                        JOptionPane.showMessageDialog(this, "Employee has been successfully"
                                + " updated", "Info", JOptionPane.INFORMATION_MESSAGE);

                        // Reset 
                        selectedEmployeeId = 0;
                    } else {
                        clear();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Double click to select the table row to edit a record",
                        "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        try {
            if (selectedEmployeeId != 0) {

                // Show input confirm dialog to ask the user 
                int result = JOptionPane.showConfirmDialog(this,
                        "Are you sure you want to delete the selected record with id "+ selectedRowEmployeeId +"", "Delete", JOptionPane.WARNING_MESSAGE);
                if (result == 0) {

                    // You cannot delete the employee information 
                    // if the employee has already a record in the payroll
                    // So we need to check the employee record status
                    // It is not advisable to delete a record of a employee
                    ArrayList<Records> recordsList = new Read(Data.RECORDS).recordList();
                    // Delete flag
                    boolean flag = false;
                    for (Records r : recordsList) {
                        if (selectedRowEmployeeId == r.getEmployeeId()) {
                            // System.out.println("id: "+ selectedRowEmployeeId);
                            flag = true;
                        }
                    }
                    // if flag is true dont delete the employee information
                    if (!flag) {
                        ArrayList<Employee> employeesList = new Read(Data.EMPLOYEE).employeeList();
                        ArrayList<Employee> newEmployeeList = new ArrayList<>();
                        for (Employee employee : employeesList) {
                            Employee e = new Employee();
                            if (selectedEmployeeId != employee.getId()) {
                                // Set the existing employee
                                e.setId(employee.getId());
                                e.setEmployeeId(employee.getEmployeeId());
                                e.setFirstName(employee.getFirstName());
                                e.setSureName(employee.getSureName());
                                e.setEmployeeTye(employee.getEmployeeTye());
                                e.setRate(employee.getRate());
                                e.setDepartmentId(employee.getDepartmentId());
                                e.setPositionId(employee.getPositionId());
                                e.setCreateAt(employee.getCreateAt());
                                newEmployeeList.add(e);
                            }
                        }
                        // Write the data again
                        Writer w = new Writer(Data.EMPLOYEE);
                        w.addEmployee(newEmployeeList);
                        // Clear
                        clear();
                        // Load the table
                        employeeTable();
                        JOptionPane.showMessageDialog(this, "Employee record has been successfully"
                                + " deleted", "Info", JOptionPane.INFORMATION_MESSAGE);
                        // Reset 
                        selectedEmployeeId = 0;
                    } else {
                        JOptionPane.showMessageDialog(this, "Unable to delete employee record."
                                + " Please contact your administrator", "Warning", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    clear();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Double click to select the table row to delete",
                        "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println("jButtonDeleteActionPerformed() -> " + "Message: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxDepartment;
    private javax.swing.JComboBox<String> jComboBoxPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonNonTeaching;
    private javax.swing.JRadioButton jRadioButtonTeaching;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JTable jTableEmployee;
    private javax.swing.JTextField jTextFieldEmployeeId;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldRate;
    private javax.swing.JTextField jTextFieldSurename;
    // End of variables declaration//GEN-END:variables
}
