
package forms;

import components.ComboItem;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import library.Read;
import components.SortPosition;
import library.Writer;
import pojo.Data;
import pojo.Department;
import pojo.Position;

/**
 *
 * @author Juanito C. Dela Cerna Jr. October 4 - 7, 2021
 */
public class AddPositionForm extends Form {
    
    private int selecetedDepartmentId;

    /**
     * Creates new form AddPosition
     */
    public AddPositionForm() {
        initComponents();
        // Initialize table
        positionTable(1);
        // Load combo box department
        comboBoxDepartment();
    }
    
    /**
     * Initialize the combo box department
     */
    public void comboBoxDepartment() {
        ArrayList<Department> departmentsList = new Read(Data.DEPARTMENT).departmentList();
        DefaultComboBoxModel jCDepartment = (DefaultComboBoxModel) jComboBoxDepartment.getModel();
        for(Department d: departmentsList){
            jCDepartment.addElement(new ComboItem(d.getId(), d.getDepartment()));
        }
    }
    
    /**
     * Load position table
     * 
     * @param departmentId 
     */
    public void positionTable(int departmentId) {
        // Position table
        DefaultTableModel table = (DefaultTableModel) jTablePosition.getModel();
        // Set the initial table row count
        table.setRowCount(0);
        // Get first the existing data
        ArrayList<Position> positionsList = new Read(Data.POSITION).positionList();
        // Sort
        Collections.sort(positionsList, new SortPosition().reversed());
        for(Position p: positionsList) {
            if(departmentId == p.getDepartmentId()) {
                Vector v = new Vector();
                v.add(p.getId());
                v.add(p.getPosition());
                table.addRow(v);
            }
        }
        jTablePosition.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPosition = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePosition = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxDepartment = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Position");
        setAlwaysOnTop(true);
        setName("Add Position"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("POSITION:");

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jTablePosition.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTablePosition.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "POSITION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePosition);
        if (jTablePosition.getColumnModel().getColumnCount() > 0) {
            jTablePosition.getColumnModel().getColumn(0).setMinWidth(40);
            jTablePosition.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jLabel2.setText("DEPARTMENT:");

        jComboBoxDepartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDepartmentItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxDepartment, 0, 183, Short.MAX_VALUE)
                            .addComponent(jTextFieldPosition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if (jTextFieldPosition.getText().length() > 0) {
            // Get first the existing data
            ArrayList<Position> positionsList = new Read(Data.POSITION).positionList();
            // Sort the list first
            Collections.sort(positionsList, new SortPosition().reversed());
            // Create a new position instance 
            Position position = new Position();
            // If the positionsList is empty, set the rowId to 1
            // If positionList is not empty get the value in index zero to add 1 
            int rowId = positionsList.isEmpty() ? 1 : positionsList.get(0).getId() + 1;
            position.setId(rowId);
            position.setDepartmentId(selecetedDepartmentId);
            position.setPosition(jTextFieldPosition.getText());
            // Add to positionList
            positionsList.add(position);
            
            // Write the text into file
            Writer writer = new Writer(Data.POSITION);
            writer.addPosition(positionsList);
            
            // Clear
            jTextFieldPosition.setText("");
            
            // load the position table
            positionTable(selecetedDepartmentId);
        } else {
            JOptionPane.showMessageDialog(this, "Please input a position name", "Warning", JOptionPane.WARNING_MESSAGE);
            jTextFieldPosition.requestFocus();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jComboBoxDepartmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDepartmentItemStateChanged
        DefaultComboBoxModel cBox = (DefaultComboBoxModel) jComboBoxDepartment.getModel();
        Object item = cBox.getSelectedItem();
        // Get the selected department id
        selecetedDepartmentId = ((ComboItem) item).getKey();
        // load the position table
        positionTable(selecetedDepartmentId);
    }//GEN-LAST:event_jComboBoxDepartmentItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPositionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPositionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPositionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPositionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPositionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxDepartment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePosition;
    private javax.swing.JTextField jTextFieldPosition;
    // End of variables declaration//GEN-END:variables
}
