/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import components.ComboItem;
import components.SortEmployee;
import components.SortPayroll;
import components.SortRecords;
import components.SortWorkingDays;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import library.Read;
import library.Writer;
import pojo.Data;
import pojo.Day;
import pojo.Employee;
import pojo.Payroll;
import pojo.Records;

/**
 *
 * @author Juanito C. Dela Cerna Jr. October 4 - 7, 2021
 */
public class AddPayrollForm extends Form {

    private int selectedEmployeeId, hours = 0, overtime = 0, absences = 0;
    
    // The limit of for adding a payroll for Employe type "Teaching"
    private int teachingDay = 5;

    /**
     * Creates new form AddPayrollForm
     */
    public AddPayrollForm() {
        initComponents();
        // Employee list
        comboBoxEmployee();
        // Days work table
        workingDaysTable(selectedEmployeeId);
    }

    /**
     * 
     * @param selectedEmployeeId 
     */
    public void workingDaysTable(int selectedEmployeeId) {
        // Days work table
        DefaultTableModel table = (DefaultTableModel) jTableWorkingDays.getModel();
        table.setRowCount(0);
        // Get the employee list
        ArrayList<Day> dayList = new Read(Data.WORKING_DAYS).workingDayList();
        Collections.sort(dayList, new SortWorkingDays().reversed());

        int totalHours = 0, totalOvertime = 0, totalAbsences = 0;
        for (Day d : dayList) {
            if (selectedEmployeeId == d.getEmployeeId()) {
                // Employee type
                if (employeeType(selectedEmployeeId).equals("Teaching")) {
                    // Get overtime for teaching employee
                    totalHours = totalHours + d.getHours();
                    totalOvertime = getOverTimeForTeachingEmployee(totalHours);
                } else {
                    // For non teaching employee
                    totalHours = totalHours + d.getHours();
                    totalOvertime = totalOvertime + d.getOvertime();
                }

                if (d.getHours() == 0) {
                    totalAbsences = totalAbsences + 1;
                }

                Vector v = new Vector();
                v.add(d.getId());
                v.add(d.getDate());
                v.add(d.getDay());
                v.add(d.getHours());
                v.add(d.getOvertime());
                table.addRow(v);
            }
        }

        hours = totalHours;
        overtime = totalOvertime;
        absences = totalAbsences;

        jLabelEmployeeType.setText("<html><font color='blue'>" + " - " + employeeType(selectedEmployeeId) + "</font></html>");
        jLabelTotalHours.setText(String.valueOf(totalHours));
        jLabelTotalOvertime.setText(String.valueOf(totalOvertime));
        jLabelTotalAbsences.setText(String.valueOf(totalAbsences));
    }

    /**
     * Initialize the combo box department
     */
    public void comboBoxEmployee() {
        // Clear combobox department
        jComboBoxEmployee.removeAllItems();
        ArrayList<Employee> employeeList = new Read(Data.EMPLOYEE).employeeList();
        Collections.sort(employeeList, new SortEmployee().reversed());
        DefaultComboBoxModel jCEmployee = (DefaultComboBoxModel) jComboBoxEmployee.getModel();
        for (Employee e : employeeList) {
            String name = e.getFirstName() + " " + e.getSureName();
            jCEmployee.addElement(new ComboItem(e.getEmployeeId(), name));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxEmployee = new javax.swing.JComboBox<>();
        jLabelEmployeeType = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelTotalHours = new javax.swing.JLabel();
        jLabelTotalOvertime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableWorkingDays = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelTotalAbsences = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Payroll");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("EMPLOYEE *");

        jComboBoxEmployee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEmployee.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEmployeeItemStateChanged(evt);
            }
        });

        jLabelEmployeeType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelEmployeeType.setText("- EMPLOYEE TYPE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEmployeeType)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jComboBoxEmployee, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelEmployeeType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("TOTAL HOURS:");

        jLabel3.setText("TOTAL OVERTIME:");

        jLabelTotalHours.setText("0");

        jLabelTotalOvertime.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotalHours)
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotalOvertime)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabelTotalHours)
                    .addComponent(jLabelTotalOvertime))
                .addContainerGap())
        );

        jTableWorkingDays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "DATE", "DAY", "HOURS", "OVERTIME"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableWorkingDays.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableWorkingDays);
        if (jTableWorkingDays.getColumnModel().getColumnCount() > 0) {
            jTableWorkingDays.getColumnModel().getColumn(0).setMinWidth(30);
            jTableWorkingDays.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jButtonAdd.setText("ADD");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        jButtonSave.setText("ADD PAYROLL");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/upload.png"))); // NOI18N
        jButtonCancel.setText("CANCEL");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("TOTAL ABSENCES:");

        jLabelTotalAbsences.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTotalAbsences, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAdd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabelTotalAbsences)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEmployeeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEmployeeItemStateChanged
        try {
            DefaultComboBoxModel cBox = (DefaultComboBoxModel) jComboBoxEmployee.getModel();
            // Class object
            Object item = cBox.getSelectedItem();
            selectedEmployeeId = ((ComboItem) item).getKey();

            workingDaysTable(selectedEmployeeId);

        } catch (NullPointerException e) {
            // System.out.println(e.getMessage());
            // Do nothin, this occur when the combobox throw a null value
        }
    }//GEN-LAST:event_jComboBoxEmployeeItemStateChanged

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        AddWorkingDays days = new AddWorkingDays(selectedEmployeeId);

        FormWindowListener formWindowListener = new FormWindowListener();
        days.addWindowListener(formWindowListener);

        days.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        days.setVisible(true);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        System.out.println("employee id: " + employeeType(selectedEmployeeId) + " rate: " + employeeRate(selectedEmployeeId) + " hour: " + hours + " overtime: " + overtime + " absences: " + absences);

        // Check the payroll tabel if is empty
        ArrayList<Day> tableDayList = new Read(Data.WORKING_DAYS).workingDayList();
        if (tableDayList.isEmpty()) {
            // show a message
            JOptionPane.showMessageDialog(this, "Payroll table is empty!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {

            try {
                ArrayList<Records> recordList = new Read(Data.RECORDS).recordList();
                Collections.sort(recordList, new SortRecords().reversed());
                Records record = new Records();
                // Record id
                int recordId = recordList.isEmpty() ? 1 : recordList.get(0).getId() + 1;
                record.setId(recordId);
                record.setEmployeeId(selectedEmployeeId);
                // Set date
                record.setDateFrom(getDate(selectedEmployeeId)[1]);
                record.setDateTo(getDate(selectedEmployeeId)[0]);
                if (employeeType(selectedEmployeeId).equals("Teaching")) {
                    // Employee salary
                    double salary = employeeTeachingSalary(selectedEmployeeId, hours, overtime, absences);
                    record.setSalary(salary);
                    // Employee data
                    Employee e = getEmployee(selectedEmployeeId);
                    record.setEmployeName(e.getFirstName() + " " + e.getSureName());
                    record.setRateOfPay(e.getRate());
                    // Overtime
                    record.setOvertimeRate(getOvertimeRate(e.getRate()));
                    // Overtime hour
                    record.setNoOvertimeHours(getOverTimeForTeachingEmployee(hours));
                    // allowance
                    record.setAllowance(getEmployeeAllowance(e.getRate()) * getNoOfHoursTeaching(hours));
                    record.setHoursAbsence(getTotalAbsencesInHour(absences));
                } else {
                    // Employee data
                    Employee e = getEmployee(selectedEmployeeId);
                    // Overtime
                    double otRate = (e.getRate() / 30) / 8;
                    // allowance, if the employee has no absent he/she is entitled for allowance
                    double allowance = absences == 0 ? (((e.getRate() / 30) / 8) * hours) * 0.1 : 0;
                    int noOfHoursAbsent = absences * 8;
                    // Deductions
                    double deductions = noOfHoursAbsent * otRate;
                    // Pay rate
                    double payRate = ((e.getRate() / 30) / 8) * hours;
                    // Employee salary
                    double salary = (payRate + otRate * overtime + allowance) - deductions;

                    record.setSalary(salary);
                    record.setEmployeName(e.getFirstName() + " " + e.getSureName());
                    record.setRateOfPay(e.getRate());
                    record.setOvertimeRate(otRate);
                    // Overtime hour
                    record.setNoOvertimeHours(overtime);
                    record.setAllowance(allowance);
                    record.setHoursAbsence(noOfHoursAbsent);
                }
                // Add object to list
                recordList.add(record);
                Writer wRecords = new Writer(Data.RECORDS);
                wRecords.addRecords(recordList);

                // Read the payroll data
                ArrayList<Payroll> payrollList = new Read(Data.PAYROLL).payrollList();
                Collections.sort(payrollList, new SortPayroll().reversed());
                // Payroll id
                int payrollId = payrollList.isEmpty() ? 1 : payrollList.get(0).getId() + 1;

                // Working days data
                ArrayList<Day> dayList = new Read(Data.WORKING_DAYS).workingDayList();
                Collections.sort(dayList, new SortWorkingDays());

                // New list
                ArrayList<Day> newDayList = new ArrayList<>();

                for (Day d : dayList) {
                    Day newDay = new Day();
                    if (selectedEmployeeId == d.getEmployeeId()) {
                        Payroll p = new Payroll();
                        p.setId(d.getId());
                        p.setEmployeeId(d.getEmployeeId());
                        p.setRecordsId(recordId);
                        p.setDate(d.getDate());
                        p.setDay(d.getDay());
                        p.setHours(d.getHours());
                        p.setOvertime(d.getOvertime());
                        payrollList.add(p);

                        // TODO - Clear the selected data
                    } else {
                        newDay.setId(d.getId());
                        newDay.setEmployeeId(d.getEmployeeId());
                        newDay.setDay(d.getDay());
                        newDay.setHours(d.getHours());
                        newDay.setOvertime(d.getOvertime());
                        newDayList.add(newDay);
                    }
                }

                // Write workings day again
                Writer w = new Writer(Data.WORKING_DAYS);
                w.addWorkingDay(newDayList);

                // Write payroll data
                Writer wPayroll = new Writer(Data.PAYROLL);
                wPayroll.addPayroll(payrollList);

                // show a message
                JOptionPane.showMessageDialog(this, "Payroll has been successfully"
                        + " recorded", "Info", JOptionPane.INFORMATION_MESSAGE);
                // Close
                this.dispose();
            } catch (Exception e) {
                // System.out.println("jButtonSaveActionPerformed() -> " + e);
                // e.getStackTrace(); 
                // show a message
                JOptionPane.showMessageDialog(this, "No payroll data found!"
                        + " Please try again", "Warning", JOptionPane.WARNING_MESSAGE);

            }
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // Check if not empty
        ArrayList<Day> dayList = new Read(Data.WORKING_DAYS).workingDayList();
        if (dayList.isEmpty()) {
            this.dispose();
        } else {
            // Show input confirm dialog to ask the user 
            int result = JOptionPane.showConfirmDialog(this,
                    "Cancel the form will errase your data ",
                    "Warning", JOptionPane.WARNING_MESSAGE);

            if (result == 0) {
                // Clear the data
                Writer w = new Writer(Data.WORKING_DAYS);
                w.clearDayList(new ArrayList<Day>());
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButtonCancelActionPerformed

    class FormWindowListener implements WindowListener {

        @Override
        public void windowOpened(WindowEvent e) {
        }

        @Override
        public void windowClosing(WindowEvent e) {
        }

        @Override
        public void windowClosed(WindowEvent e) {
            workingDaysTable(selectedEmployeeId);
        }

        @Override
        public void windowIconified(WindowEvent e) {
        }

        @Override
        public void windowDeiconified(WindowEvent e) {
        }

        @Override
        public void windowActivated(WindowEvent e) {
        }

        @Override
        public void windowDeactivated(WindowEvent e) {
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPayrollForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPayrollForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPayrollForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPayrollForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPayrollForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEmployeeType;
    private javax.swing.JLabel jLabelTotalAbsences;
    private javax.swing.JLabel jLabelTotalHours;
    private javax.swing.JLabel jLabelTotalOvertime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableWorkingDays;
    // End of variables declaration//GEN-END:variables
}
