
package forms;

import components.SortWorkingDays;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import library.Read;
import library.Writer;
import pojo.Data;
import pojo.Day;

/**
 *
 * @author  Juanito C. Dela Cerna Jr. October 4 - 7, 2021
 */
public class AddWorkingDays extends Form {

    private int selectedEmployeeId;

    public AddWorkingDays() {
    }

    /**
     * Creates new form AddWorkingDays
     */
    public AddWorkingDays(int employeeId) {
        selectedEmployeeId = employeeId;
        initComponents();
        
        
        // Working day data
        ArrayList<Day> dayList = new Read(Data.WORKING_DAYS).workingDayList();
        Collections.sort(dayList, new SortWorkingDays());
        int day = 1;
        
        // Get employee type
        if(employeeType(selectedEmployeeId).equals("Teaching")) {
            for (Day d : dayList) {
                if (selectedEmployeeId == d.getEmployeeId()) {
                    day = d.getDay() + 1;
                }
            }
            // Disable the input if the day is greate than 5
            // System.out.println(day);
            if(day > 5) {
                jLabelInformation.setText("Maximum is 5 days only for employee type Teaching.");
                jTextFieldDate.setEditable(false);
                jTextFieldDay.setEditable(false);
                jTextFieldHours.setEditable(false);
                jTextFieldOvertime.setEditable(false);
                jButtonSave.setEnabled(false);
                jButtonCancel.setEnabled(false);
            } else {
                jLabelInformation.setText("Day and Overtime is diabled by default.");
                jLabelInformation1.setText("Automatically computed for employee type Teaching.");
            }
            jTextFieldOvertime.setText("0");
            jTextFieldOvertime.setEditable(false);
        } else {
            jLabelInformation.setText("Day is diabled by default.");
            jLabelInformation1.setText("Automatically generated by the system.");
            // Get employee type
            for (Day d : dayList) {
                if (selectedEmployeeId == d.getEmployeeId()) {
                    day = d.getDay() + 1;
                }
            }
        }
        jLabelNote.setText("Enter a zero (0) value in HOURS for absent");
        jTextFieldDay.setText(String.valueOf(day));
        jTextFieldDay.setEditable(false);
    }

   
    /**
     * Check employee id
     *
     * @param employeeId
     */
    public int findDayById(int dayId) {
        // Get the list
        ArrayList<Day> dayList = new Read(Data.WORKING_DAYS).workingDayList();
        for (Day d : dayList) {
            if (dayId == d.getDay() && selectedEmployeeId == d.getEmployeeId()) {
                return 1;
            }
        }
        return 0;
    }

    /**
     * Validate all the user input
     *
     * @return 0 to input again and 1 for valid input
     */
    public int inputValidation() {
        String date = dateFieldValidation("Date", jTextFieldDate);
        if (date.isEmpty()) {
            return 0;
        }
        
        String day = numberFieldValidation("Day", jTextFieldDay);
        if (day.isEmpty()) {
            return 0;
        }

        String hours = workingHoursValidation("Hours", employeeType(selectedEmployeeId), jTextFieldHours);
        if (hours.isEmpty()) {
            return 0;
        }

        String overtime = oTValidation("Overtime", "Non - Teaching", jTextFieldOvertime);
        if (overtime.isEmpty()) {
            return 0;
        }

        return 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelbody = new javax.swing.JPanel();
        jTextFieldDay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldHours = new javax.swing.JTextField();
        jTextFieldOvertime = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jLabelNote = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelInformation = new javax.swing.JLabel();
        jLabelInformation1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Day");
        setAlwaysOnTop(true);
        setResizable(false);

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));

        jPanelbody.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("HOURS:");

        jLabel1.setText("DAY:");

        jLabel3.setText("OVERTIME:");

        jButtonSave.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        jButtonSave.setText("SAVE");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/upload.png"))); // NOI18N
        jButtonCancel.setText("CANCEL");
        jButtonCancel.setToolTipText("");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel4.setText("DATE:");

        jLabelNote.setText("...");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("YYYY-dd-mm");

        javax.swing.GroupLayout jPanelbodyLayout = new javax.swing.GroupLayout(jPanelbody);
        jPanelbody.setLayout(jPanelbodyLayout);
        jPanelbodyLayout.setHorizontalGroup(
            jPanelbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelbodyLayout.createSequentialGroup()
                        .addComponent(jButtonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelbodyLayout.createSequentialGroup()
                        .addGroup(jPanelbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNote)
                            .addComponent(jTextFieldDay)
                            .addComponent(jTextFieldHours)
                            .addComponent(jTextFieldOvertime)
                            .addComponent(jTextFieldDate, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelbodyLayout.setVerticalGroup(
            jPanelbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNote)
                .addGap(4, 4, 4)
                .addGroup(jPanelbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelHeader.setBackground(new java.awt.Color(255, 255, 255));

        jLabelInformation.setText("...");

        jLabelInformation1.setText("...");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInformation1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(jLabelInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelInformation1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelbody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelbody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        try {
            if (inputValidation() == 1) {
                int inputDay = Integer.parseInt(jTextFieldDay.getText());
                if (findDayById(inputDay) == 0) {

                    ArrayList<Day> dayList = new Read(Data.WORKING_DAYS).workingDayList();
                    Collections.sort(dayList, new SortWorkingDays().reversed());
                    Day day = new Day();
                    day.setId(dayList.isEmpty() ? 1 : dayList.get(0).getId() + 1);
                    day.setEmployeeId(selectedEmployeeId);
                    day.setDate(jTextFieldDate.getText());
                    day.setDay(Integer.parseInt(jTextFieldDay.getText()));
                    day.setHours(Integer.parseInt(jTextFieldHours.getText()));
                    day.setOvertime(Integer.parseInt(jTextFieldOvertime.getText()));
                    dayList.add(day);

                    Writer w = new Writer(Data.WORKING_DAYS);
                    w.addWorkingDay(dayList);

                    JOptionPane.showMessageDialog(this, "Day has been successfully"
                            + " added", "Info", JOptionPane.INFORMATION_MESSAGE);

                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "The Day " + inputDay
                        + " is already recorded", "Info", JOptionPane.INFORMATION_MESSAGE);
                        jTextFieldDay.requestFocus();
                }
            }
        } catch (Exception e) {
            System.out.println("jButtonSaveActionPerformed() -> " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddWorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddWorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddWorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddWorkingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddWorkingDays().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelInformation;
    private javax.swing.JLabel jLabelInformation1;
    private javax.swing.JLabel jLabelNote;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelbody;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldDay;
    private javax.swing.JTextField jTextFieldHours;
    private javax.swing.JTextField jTextFieldOvertime;
    // End of variables declaration//GEN-END:variables
}
