/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.util.ArrayList;
import library.Read;
import library.Writer;
import pojo.Data;
import pojo.EditWorkingDays;

/**
 *
 * @author User
 */
public class EditWorkingDayForm extends Form {

    private int selectedEmployeeId, selectedRecordId, selectedTableRow;

    private EditWorkingDayForm() {
    }

    /**
     * Creates new form EditWorkingDayForm
     *
     * @param selectedRecordId
     */
    public EditWorkingDayForm(int selectedEmployeeId, int selectedRecordId, int selectedTableRow) {
        this.selectedRecordId = selectedRecordId;
        this.selectedTableRow = selectedTableRow;
        this.selectedEmployeeId = selectedEmployeeId;
        initComponents();
        setTextField();
    }

    /**
     * Set the data into text field
     */
    public void setTextField() {
        // Get the data gain
        ArrayList<EditWorkingDays> workingDaysList = new Read(Data.EDIT_WORKING_DAYS).editWorkingDaysList();
        for (EditWorkingDays e : workingDaysList) {
            if (selectedRecordId == e.getRecordId() && selectedTableRow == e.getId()) {
                jTextFieldDate.setText(String.valueOf(e.getDate()));
                jTextFieldDay.setText(String.valueOf(e.getDay()));
                jTextFieldDay.setEditable(false);
                jTextFieldHours.setText(String.valueOf(e.getHours()));
                jTextFieldOvertime.setText(String.valueOf(e.getOvertime()));
            }
        }

        // Disabled the overtime for wmployee type Teaching
        if (employeeType(selectedEmployeeId).equals("Teaching")) {
            jTextFieldOvertime.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jTextFieldDay = new javax.swing.JTextField();
        jTextFieldHours = new javax.swing.JTextField();
        jTextFieldOvertime = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabelNote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update record");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("DATE:");

        jLabel2.setText("DAY:");

        jLabel3.setText("HOURS:");

        jLabel4.setText("OVERTIME:");

        jTextFieldDay.setEditable(false);
        jTextFieldDay.setBackground(new java.awt.Color(153, 153, 153));

        jButtonCancel.setText("CANCEL");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jLabelNote.setText("Enter a zero (0) value in HOURS for absent");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNote)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldDate)
                                .addComponent(jTextFieldDay)
                                .addComponent(jTextFieldHours)
                                .addComponent(jTextFieldOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabelNote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * Validate all the user input
     *
     * @return 0 to input again and 1 for valid input
     */
    public int inputValidation() {
        String date = dateFieldValidation("Date", jTextFieldDate);
        if (date.isEmpty()) {
            return 0;
        }
        
        String day = numberFieldValidation("Day", jTextFieldDay);
        if (day.isEmpty()) {
            return 0;
        }

        String hours = workingHoursValidation("Hours", employeeType(selectedEmployeeId), jTextFieldHours);
        if (hours.isEmpty()) {
            return 0;
        }

        String overtime = oTValidation("Overtime", "Non - Teaching", jTextFieldOvertime);
        if (overtime.isEmpty()) {
            return 0;
        }

        return 1;
    }
    
    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        try {
            if (inputValidation() == 1) {
                // Get the data gain
                ArrayList<EditWorkingDays> workingDaysList = new Read(Data.EDIT_WORKING_DAYS).editWorkingDaysList();
                ArrayList<EditWorkingDays> newWorkingDaysList = new ArrayList<>();
                for (EditWorkingDays e : workingDaysList) {
                    EditWorkingDays newDay = new EditWorkingDays();
                    if (selectedRecordId == e.getRecordId() && selectedTableRow == e.getId()) {
                        // System.out.println("selectedTableRow: "+ selectedTableRow+ " selectedRecordId: " + selectedRecordId);
                        newDay.setId(e.getId());
                        newDay.setRecordId(e.getRecordId());
                        newDay.setEmployeeId(selectedEmployeeId);
                        newDay.setDate(jTextFieldDate.getText());
                        newDay.setDay(Integer.parseInt(jTextFieldDay.getText()));
                        newDay.setHours(Integer.parseInt(jTextFieldHours.getText()));
                        newDay.setOvertime(Integer.parseInt(jTextFieldOvertime.getText()));
                    } else {
                        newDay.setId(e.getId());
                        newDay.setRecordId(e.getRecordId());
                        newDay.setEmployeeId(selectedEmployeeId);
                        newDay.setDate(e.getDate());
                        newDay.setDay(e.getDay());
                        newDay.setHours(e.getHours());
                        newDay.setOvertime(e.getOvertime());
                    }
                    newWorkingDaysList.add(newDay);
                }
                // Write the data again
                Writer w = new Writer(Data.EDIT_WORKING_DAYS);
                w.addEditWorkingsDay(newWorkingDaysList);
                this.dispose();
            }
        } catch (Exception e) {
            System.out.println("jButtonUpdateActionPerformed() -> " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditWorkingDayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditWorkingDayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditWorkingDayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditWorkingDayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditWorkingDayForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelNote;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldDay;
    private javax.swing.JTextField jTextFieldHours;
    private javax.swing.JTextField jTextFieldOvertime;
    // End of variables declaration//GEN-END:variables
}
