package forms;

import components.SortRecords;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import library.Read;
import library.Writer;
import pojo.Data;
import pojo.Payroll;
import pojo.Records;

/**
 *
 * @author Juanito C. Dela Cerna Jr. October 4 - 7, 2021
 */
public class MainForm extends Form {

    private int selectedRow, selectedEmployeeId;

    /**
     * Creates new form Main
     */
    public MainForm() {
        initComponents();

        selectedEmployeeId = 0;
        String txtNote1 = "  Note: Double click the ";
        String txtNote2 = "  table row to select a record.";
        jLabelNote.setText("<html>" + txtNote1 + "<br>" + txtNote2 + "</html?");
        
        // Records table
        recordsTable();
    }

    /**
     * Records table
     */
    public void recordsTable() {
        // Days work table
        DefaultTableModel table = (DefaultTableModel) jTablePayrollRecords.getModel();
        table.setRowCount(0);
        // Get the employee list
        ArrayList<Records> recordList = new Read(Data.RECORDS).recordList();
        Collections.sort(recordList, new SortRecords().reversed());

        for (Records r : recordList) {
            Vector v = new Vector();
            v.add(r.getId());
            v.add(r.getEmployeeId());
            v.add(r.getEmployeName());
            v.add(r.getDateFrom());
            v.add(r.getDateTo());
            v.add(r.getSalary());
            v.add(r.getRateOfPay());
            v.add(r.getOvertimeRate());
            v.add(r.getAllowance());
            v.add(r.getNoOvertimeHours());
            v.add(r.getHoursAbsence());
            table.addRow(v);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelLeft = new javax.swing.JPanel();
        jButtonAddPayroll = new javax.swing.JButton();
        jButtonEditPayroll = new javax.swing.JButton();
        jButtonViewPayroll = new javax.swing.JButton();
        jButtonDeletePayroll = new javax.swing.JButton();
        jLabelNote = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelSelectedRow = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanelRigth = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePayrollRecords = new javax.swing.JTable();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemAddEmployee = new javax.swing.JMenuItem();
        jMenuItemAddDepartment = new javax.swing.JMenuItem();
        jMenuItemAddPosition = new javax.swing.JMenuItem();
        jMenuItemGenPayrollReport = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuSettings = new javax.swing.JMenu();
        jMenuItemOptions = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main - ABCS Institute Payroll System");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanelLeft.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLeft.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonAddPayroll.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAddPayroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        jButtonAddPayroll.setText("ADD PAYROLL");
        jButtonAddPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPayrollActionPerformed(evt);
            }
        });

        jButtonEditPayroll.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEditPayroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/redact.png"))); // NOI18N
        jButtonEditPayroll.setText("EDIT PAYROLL");
        jButtonEditPayroll.setToolTipText("EDIT PAYROLL");
        jButtonEditPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPayrollActionPerformed(evt);
            }
        });

        jButtonViewPayroll.setBackground(new java.awt.Color(255, 255, 255));
        jButtonViewPayroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/data.png"))); // NOI18N
        jButtonViewPayroll.setText("VIEW PAYROLL");
        jButtonViewPayroll.setToolTipText("VIEW PAYROLL");
        jButtonViewPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewPayrollActionPerformed(evt);
            }
        });

        jButtonDeletePayroll.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDeletePayroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/select.png"))); // NOI18N
        jButtonDeletePayroll.setText("DELETE PAYROLL");
        jButtonDeletePayroll.setToolTipText("DELETE PAYROLL");
        jButtonDeletePayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePayrollActionPerformed(evt);
            }
        });

        jLabelNote.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNote.setText("  Note:");
        jLabelNote.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel1.setText("Selected row: #");

        jLabelSelectedRow.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelSelectedRow.setForeground(new java.awt.Color(0, 0, 102));
        jLabelSelectedRow.setText("0");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanelLeftLayout = new javax.swing.GroupLayout(jPanelLeft);
        jPanelLeft.setLayout(jPanelLeftLayout);
        jPanelLeftLayout.setHorizontalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddPayroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonViewPayroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonDeletePayroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelLeftLayout.createSequentialGroup()
                        .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanelLeftLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSelectedRow)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelLeftLayout.setVerticalGroup(
            jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddPayroll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditPayroll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonViewPayroll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeletePayroll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNote, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(jPanelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelSelectedRow))
                .addContainerGap())
        );

        jLabelNote.getAccessibleContext().setAccessibleName("             ");

        jPanelRigth.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRigth.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setAutoscrolls(true);

        jTablePayrollRecords.setBackground(new java.awt.Color(240, 240, 240));
        jTablePayrollRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "EMP ID", "EMPLOYEE NAME", "(DATE) FROM", "(DATE) TO", "SALARY", "RATE PER HOUR / MONTHLY", "OT RATE", "ALLOWANCE", "OT HOURS", "(H) ABSENCES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePayrollRecords.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTablePayrollRecords.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTablePayrollRecords.setFillsViewportHeight(true);
        jTablePayrollRecords.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTablePayrollRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePayrollRecordsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePayrollRecords);
        if (jTablePayrollRecords.getColumnModel().getColumnCount() > 0) {
            jTablePayrollRecords.getColumnModel().getColumn(0).setMinWidth(30);
            jTablePayrollRecords.getColumnModel().getColumn(0).setMaxWidth(30);
            jTablePayrollRecords.getColumnModel().getColumn(1).setMinWidth(50);
            jTablePayrollRecords.getColumnModel().getColumn(1).setMaxWidth(50);
            jTablePayrollRecords.getColumnModel().getColumn(2).setMinWidth(150);
            jTablePayrollRecords.getColumnModel().getColumn(5).setMinWidth(40);
            jTablePayrollRecords.getColumnModel().getColumn(6).setMinWidth(150);
            jTablePayrollRecords.getColumnModel().getColumn(10).setMinWidth(100);
        }

        javax.swing.GroupLayout jPanelRigthLayout = new javax.swing.GroupLayout(jPanelRigth);
        jPanelRigth.setLayout(jPanelRigthLayout);
        jPanelRigthLayout.setHorizontalGroup(
            jPanelRigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRigthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1069, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRigthLayout.setVerticalGroup(
            jPanelRigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRigthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRigth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelRigth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jMenuBarMain.setPreferredSize(new java.awt.Dimension(105, 30));

        jMenuFile.setText("File");

        jMenuItemAddEmployee.setText("Add Employee");
        jMenuItemAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddEmployeeActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemAddEmployee);

        jMenuItemAddDepartment.setText("Add Deparment");
        jMenuItemAddDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddDepartmentActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemAddDepartment);

        jMenuItemAddPosition.setText("Add Position");
        jMenuItemAddPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddPositionActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemAddPosition);

        jMenuItemGenPayrollReport.setText("Generate Payroll Reports");
        jMenuItemGenPayrollReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenPayrollReportActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemGenPayrollReport);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBarMain.add(jMenuFile);

        jMenuSettings.setText("Settings");

        jMenuItemOptions.setText("Options");
        jMenuItemOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOptionsActionPerformed(evt);
            }
        });
        jMenuSettings.add(jMenuItemOptions);

        jMenuBarMain.add(jMenuSettings);

        jMenuHelp.setText("Help");

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBarMain.add(jMenuHelp);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddEmployeeActionPerformed
        AddEmployeeForm addEmployee = new AddEmployeeForm();
        addEmployee.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addEmployee.setVisible(true);
    }//GEN-LAST:event_jMenuItemAddEmployeeActionPerformed

    private void jButtonEditPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPayrollActionPerformed
         try {
            if (selectedEmployeeId != 0 && selectedRow != 0) {
                
                EditPayrollForm editPayrollForm = new EditPayrollForm(selectedEmployeeId, selectedRow);
                // Listener
                FormWindowListener listener = new FormWindowListener();
                editPayrollForm.addWindowListener(listener);
                editPayrollForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                editPayrollForm.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(this, "Double click the table row to update a record",
                        "Info", JOptionPane.INFORMATION_MESSAGE);
            }
            selectedRow = 0;
        } catch (Exception e) {
            System.out.println("jButtonDeletePayrollActionPerformed() -> " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonEditPayrollActionPerformed

    private void jMenuItemAddDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddDepartmentActionPerformed
        AddDepartmentForm addDepartment = new AddDepartmentForm();
        addDepartment.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addDepartment.setVisible(true);
    }//GEN-LAST:event_jMenuItemAddDepartmentActionPerformed

    private void jMenuItemAddPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddPositionActionPerformed
        AddPositionForm addPosition = new AddPositionForm();
        addPosition.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addPosition.setVisible(true);
    }//GEN-LAST:event_jMenuItemAddPositionActionPerformed

    private void jButtonAddPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPayrollActionPerformed
        AddPayrollForm addPayrollForm = new AddPayrollForm();

        // Add listener
        FormWindowListener formWindowListener = new FormWindowListener();
        addPayrollForm.addWindowListener(formWindowListener);

        addPayrollForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addPayrollForm.setVisible(true);
    }//GEN-LAST:event_jButtonAddPayrollActionPerformed

    private void jButtonDeletePayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePayrollActionPerformed
        try {
            if (selectedEmployeeId != 0 && selectedRow != 0) {
                // Show input confirm dialog to ask the user 
                int result = JOptionPane.showConfirmDialog(this,
                        "Are you sure you want to delete the selected record with row no. "
                        + selectedRow + "?", "Delete", JOptionPane.WARNING_MESSAGE);
                if (result == 0) {
                    // Get the employee list
                    ArrayList<Records> recordList = new Read(Data.RECORDS).recordList();
                    ArrayList<Records> newRecordList = new ArrayList<>();
                    // Selected record id
                    int selectedRecordId = 0;
                    for(Records r: recordList) {
                        if(selectedRow != r.getId()) {
                            Records rec = new Records();
                            rec.setId(r.getId());
                            rec.setEmployeeId(r.getEmployeeId());
                            rec.setEmployeName(r.getEmployeName());
                            rec.setDateFrom(r.getDateFrom());
                            rec.setDateTo(r.getDateTo());
                            rec.setSalary(r.getSalary());
                            rec.setRateOfPay(r.getRateOfPay());
                            rec.setOvertimeRate(r.getOvertimeRate());
                            rec.setAllowance(r.getAllowance());
                            rec.setNoOvertimeHours(r.getNoOvertimeHours());
                            rec.setHoursAbsence(r.getHoursAbsence());
                            newRecordList.add(rec);
                        } else {
                            selectedRecordId = r.getId();
                        }
                    }
                    // New Records list
                    Writer w = new Writer(Data.RECORDS);
                    w.addRecords(newRecordList);
                    
                    // Clear the deleted payroll details
                    // Insert the payroll new list
                    ArrayList<Payroll> payrollList = new Read(Data.PAYROLL).payrollList();
                    ArrayList<Payroll> newPayrollList = new ArrayList<>();
                    for(Payroll p: payrollList) {
                        if(selectedRecordId != p.getRecordsId()) {
                            Payroll payroll = new Payroll();
                            payroll.setId(p.getId());
                            payroll.setEmployeeId(p.getEmployeeId());
                            payroll.setRecordsId(p.getRecordsId());
                            payroll.setDate(p.getDate());
                            payroll.setDay(p.getDay());
                            payroll.setHours(p.getHours());
                            payroll.setOvertime(p.getOvertime());
                            newPayrollList.add(payroll);
                        }
                    }
                    // Write the new payroll data
                    Writer wNewPayroll = new Writer(Data.PAYROLL);
                    wNewPayroll.addPayroll(newPayrollList);
                    
                    // Load the table
                    //recordsTable();
                    selectedRow = 0;
                    selectedEmployeeId = 0;
                } else {
                    selectedRow = 0;
                    selectedEmployeeId = 0;
                }
                // Load the table
                recordsTable();
                jLabelSelectedRow.setText("...");
            } else {
                JOptionPane.showMessageDialog(this, "Double click the table row to delete a record",
                        "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println("jButtonDeletePayrollActionPerformed() -> " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeletePayrollActionPerformed

    private void jTablePayrollRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePayrollRecordsMouseClicked
        try {
            // Days work table
            DefaultTableModel table = (DefaultTableModel) jTablePayrollRecords.getModel();
            int selected = jTablePayrollRecords.getSelectedRow();
            selectedRow = Integer.parseInt(table.getValueAt(selected, 0).toString());
            selectedEmployeeId = Integer.parseInt(table.getValueAt(selected, 1).toString());
            // Set jLabelSelectedRow the selected row
            jLabelSelectedRow.setText(String.valueOf(selectedRow));
        } catch (Exception e) {
            System.out.println("jTablePayrollRecordsMouseClicked() -> " + e.getMessage());
        }
    }//GEN-LAST:event_jTablePayrollRecordsMouseClicked

    private void jButtonViewPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewPayrollActionPerformed
        try {
            if (selectedEmployeeId != 0 && selectedRow != 0) {
                ViewPayrollForm v = new ViewPayrollForm(selectedEmployeeId, selectedRow);
                v.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                v.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Double click the table row to view the record details",
                        "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println("jButtonEditPayrollActionPerformed() -> " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonViewPayrollActionPerformed

    private void jMenuItemGenPayrollReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenPayrollReportActionPerformed
        JOptionPane.showMessageDialog(this, "Generate payroll reports feature not implemented yet!",
                "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItemGenPayrollReportActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOptionsActionPerformed
        JOptionPane.showMessageDialog(this, "Options feature not implemented yet!",
                "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItemOptionsActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        JOptionPane.showMessageDialog(this, "<html>DICT Case Study Module 2"
                + "<br>Duration: 4 days "
                + "<br>Date: September 4 - 7, 2021"
                + "<br>Created by: Juanito C. Dela Cerna Jr.</html>",
                "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    class FormWindowListener implements WindowListener {

        @Override
        public void windowOpened(WindowEvent e) {
        }

        @Override
        public void windowClosing(WindowEvent e) {
        }

        @Override
        public void windowClosed(WindowEvent e) {
            recordsTable();
            selectedRow = 0;
            jLabelSelectedRow.setText("...");
        }

        @Override
        public void windowIconified(WindowEvent e) {
        }

        @Override
        public void windowDeiconified(WindowEvent e) {
        }

        @Override
        public void windowActivated(WindowEvent e) {
        }

        @Override
        public void windowDeactivated(WindowEvent e) {
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddPayroll;
    private javax.swing.JButton jButtonDeletePayroll;
    private javax.swing.JButton jButtonEditPayroll;
    private javax.swing.JButton jButtonViewPayroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNote;
    private javax.swing.JLabel jLabelSelectedRow;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemAddDepartment;
    private javax.swing.JMenuItem jMenuItemAddEmployee;
    private javax.swing.JMenuItem jMenuItemAddPosition;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemGenPayrollReport;
    private javax.swing.JMenuItem jMenuItemOptions;
    private javax.swing.JMenu jMenuSettings;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelLeft;
    private javax.swing.JPanel jPanelRigth;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePayrollRecords;
    // End of variables declaration//GEN-END:variables
}
